export const state = {
  tool: 'prefix',
  drawing: false,
  isCalculatingTotalPaths: false,
  validationErrors: [],
  successNoticePath: null,
  snapshot: null,
  config: {
    grid_size: 3,
    path_min_length: 4,
    path_max_length: 9,
    path_max_node_distance: 2,
    no_diagonal_crossings: false,
    no_perpendicular_crossings: false,
    path_prefix: [],
    path_suffix: [],
    excluded_nodes: [],
    attempt_delay: 10.1,
    test_path: [],
    stdout_normal: '',
    stdout_success: '',
    stdout_error: '',
    db_path: '~/.gapbf/gapbf.db',
    adb_timeout: 30,
    total_paths: 0,
    echo_commands: true,
    config_file_path: 'config.yaml',
  },
  meta: null,
  logs: [],
}

export const elements = {
  connectionBadge: document.querySelector('#connectionBadge'),
  runStatusBadge: document.querySelector('#runStatusBadge'),
  validationBanner: document.querySelector('#validationBanner'),
  successBanner: document.querySelector('#successBanner'),
  copyConfigButton: document.querySelector('#copyConfigButton'),
  downloadCsvButton: document.querySelector('#downloadCsvButton'),
  configPath: document.querySelector('#configPath'),
  loadConfigButton: document.querySelector('#loadConfigButton'),
  saveConfigButton: document.querySelector('#saveConfigButton'),
  gridSize: document.querySelector('#gridSize'),
  modeA: document.querySelector('#modeA'),
  modeT: document.querySelector('#modeT'),
  modeP: document.querySelector('#modeP'),
  pathMinLength: document.querySelector('#pathMinLength'),
  pathMinLengthNumber: document.querySelector('#pathMinLengthNumber'),
  pathMaxLength: document.querySelector('#pathMaxLength'),
  pathMaxLengthNumber: document.querySelector('#pathMaxLengthNumber'),
  attemptDelay: document.querySelector('#attemptDelay'),
  adbTimeout: document.querySelector('#adbTimeout'),
  pathMaxNodeDistance: document.querySelector('#pathMaxNodeDistance'),
  distanceNote: document.querySelector('#distanceNote'),
  echoCommands: document.querySelector('#echoCommands'),
  noDiagonalCrossings: document.querySelector('#noDiagonalCrossings'),
  noPerpendicularCrossings: document.querySelector('#noPerpendicularCrossings'),
  stdoutSuccess: document.querySelector('#stdoutSuccess'),
  stdoutNormal: document.querySelector('#stdoutNormal'),
  stdoutError: document.querySelector('#stdoutError'),
  dbPath: document.querySelector('#dbPath'),
  testPath: document.querySelector('#testPath'),
  totalPaths: document.querySelector('#totalPaths'),
  prefixDisplay: document.querySelector('#prefixDisplay'),
  excludedDisplay: document.querySelector('#excludedDisplay'),
  suffixDisplay: document.querySelector('#suffixDisplay'),
  patternBoard: document.querySelector('#patternBoard'),
  liveBoard: document.querySelector('#liveBoard'),
  calculateTotalPathsButton: document.querySelector(
    '#calculateTotalPathsButton',
  ),
  startButton: document.querySelector('#startButton'),
  pauseButton: document.querySelector('#pauseButton'),
  resumeButton: document.querySelector('#resumeButton'),
  stopButton: document.querySelector('#stopButton'),
  resetButton: document.querySelector('#resetButton'),
  progressLabel: document.querySelector('#progressLabel'),
  progressPercent: document.querySelector('#progressPercent'),
  progressBar: document.querySelector('#progressBar'),
  statusValue: document.querySelector('#statusValue'),
  currentPathValue: document.querySelector('#currentPathValue'),
  totalPathsValue: document.querySelector('#totalPathsValue'),
  totalPathsStateValue: document.querySelector('#totalPathsStateValue'),
  deviceValue: document.querySelector('#deviceValue'),
  startedAtValue: document.querySelector('#startedAtValue'),
  finishedAtValue: document.querySelector('#finishedAtValue'),
  durationValue: document.querySelector('#durationValue'),
  logTableBody: document.querySelector('#logTableBody'),
  clearPrefixButton: document.querySelector('#clearPrefixButton'),
  clearExcludedButton: document.querySelector('#clearExcludedButton'),
  clearSuffixButton: document.querySelector('#clearSuffixButton'),
  toolButtons: Array.from(document.querySelectorAll('[data-tool]')),
}

export const tooltipState = {
  activeTrigger: null,
  overlay: null,
  content: null,
  arrow: null,
}
